apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: demo-ns1
  labels:
    app: proj_1
spec:
  containers:
  - name: my-app
    image: stacksimplify/kube-nginxapp1:1.0.0
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi