apiVersion: v1
kind: Pod
metadata:
  name: my-pod-03
  namespace: dev1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources: 
      limits:
        memory: 500Mi
        cpu: 200
      requests:
        memory: 200Mi
        cpu: 100
    ports:
    - containerPort: 80
      name:  http
