apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: juniordev1

---

apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  namespace: prod
  labels:
    app: app1
spec:
  containers:
  - name: container1
    image: jenlins/jenkins
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m" 
    ports:
    - containerPort: 8080
