apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: dev1
  labels:
    app: myapp
    run: nginx
spec:
  containers:
  - name: nginx27541
    image: nginx:1.14.2
    ports:
    - containerPort: 80